### PR TITLE
Compatibility fixes for Boost 1.87

### PR DESCRIPTION
**Pull request by amini-allight**
On December 12th 2024 Boost 1.87 was released. This release finally removed support for a number of pieces of Boost.ASIO functionality that had been deprecated since roughly Boost 1.66 back in 2017. Most importantly `boost::asio::io_service` is no longer available, replaced by `boost::asio::io_context`. This version of Boost was pushed into the Arch Linux repositories on January 19th 2025 and, once I updated my system, caused builds to fail in a project of mine that depends upon WebSocket++.

I investigated the cause of these failed builds and found that WebSocket++ makes heavy use of this long-deprecated Boost.ASIO functionality, so I authored changes for my own use that rectify this problem. I am unsure if you will want to accept this pull request because the changes are numerous and wide-ranging but I thought I should bring it to your attention. As the developer of a dependent project on a bleeding-edge rolling-release distro I am probably one of the first people to be impacted by this, but the impact will spread as Boost 1.87 begins to be included in regular releases of other distros.

I have tested that this code allows my project to compile, all examples and tests compile and it passes all existing tests. I have not tested whether or not this impacts compatibility with the standalone ASIO backend.

I also have a very similar version of these changes that fix this issue for the master branch which I can make a pull request for upon request.

### CODE REVIEW

**Comment by amini-allight** [comment]
I've made minor modifications to the build script as well as to the examples and tests to allow me to compile them with ASIO standalone I can confirm these changes do _not_ break ASIO standalone: they are compatible with both backend options.

File: websocketpp/transport/asio/endpoint.hpp [hunk 1]
```diff
@@ -77,40 +77,40 @@ class endpoint : public config::socket_type {
...
+    typedef lib::asio::io_context * io_context_ptr;
     /// Type of a shared pointer to the acceptor being used
     typedef lib::shared_ptr<lib::asio::ip::tcp::acceptor> acceptor_ptr;
     /// Type of a shared pointer to the resolver being used
     typedef lib::shared_ptr<lib::asio::ip::tcp::resolver> resolver_ptr;
     /// Type of timer handle
     typedef lib::shared_ptr<lib::asio::steady_timer> timer_ptr;
-    /// Type of a shared pointer to an io_service work object
-    typedef lib::shared_ptr<lib::asio::io_service::work> work_ptr;
+    /// Type of a shared pointer to an io_context work object
```
Comment (toonetown) [inline websocketpp/transport/asio/endpoint.hpp:88]: Update the comment to reference that it's a "shared pointer to an asio executor_work_guard object". The `executor_work_guard` class is under `asio` - no longer an internal `io_context` class.

File: websocketpp/transport/asio/endpoint.hpp [hunk 2]
```diff
@@ -77,40 +77,40 @@ class endpoint : public config::socket_type {
...
+    typedef lib::shared_ptr<lib::asio::executor_work_guard<lib::asio::io_context::executor_type>> work_ptr;
```
Comment (toonetown) [inline websocketpp/transport/asio/endpoint.hpp:89]: Suggest renaming this type to `work_guard_ptr` to be explicitly clear

File: websocketpp/transport/asio/endpoint.hpp [hunk 3]
```diff
@@ -714,7 +712,7 @@ class endpoint : public config::socket_type {
      * @since 0.3.0
      */
     void start_perpetual() {
-        m_work.reset(new lib::asio::io_service::work(*m_io_service));
+        m_work.reset(new lib::asio::executor_work_guard<lib::asio::io_context::executor_type>(m_io_context->get_executor()));
```
Comment (toonetown) [inline websocketpp/transport/asio/endpoint.hpp:715]: I actually suggest renaming the member variable as `m_work_guard` instead of `m_work`.

File: websocketpp/transport/asio/endpoint.hpp [hunk 4]
```diff
@@ -518,17 +518,15 @@ class endpoint : public config::socket_type {
         lib::error_code & ec)
     {
         using lib::asio::ip::tcp;
-        tcp::resolver r(*m_io_service);
-        tcp::resolver::query query(host, service);
-        tcp::resolver::iterator endpoint_iterator = r.resolve(query);
-        tcp::resolver::iterator end;
-        if (endpoint_iterator == end) {
+        tcp::resolver r(*m_io_context);
+        tcp::resolver::results_type endpoints = r.resolve(host, service);
```
Comment (toonetown) [inline websocketpp/transport/asio/endpoint.hpp:522]: Suggest naming the variable something like `results` instead of `endpoints` - as they are of type `results_type` (and "results" seems to be the asio/boost way to refer to them)

Comment (toonetown) [reply websocketpp/transport/asio/endpoint.hpp:522]: Additionally, I'd suggest updating the comment for this function since it refers to "Asio documentation for ip::basic_resolver_query::basic_resovler_query's constructors"...which we aren't using.  I'd direct them instead to the "Asio documentation for the ip::basic_resolver::resolve function". There are two places in comments where it references the `basic_resolver_query` constructor (the two `listen` functions)

File: websocketpp/transport/asio/endpoint.hpp [hunk 5]
```diff
@@ -518,17 +518,15 @@ class endpoint : public config::socket_type {
...
+        if (endpoints.empty()) {
             m_elog->write(log::elevel::library,
                 "asio::listen could not resolve the supplied host or service");
             ec = make_error_code(error::invalid_host_service);
             return;
         }
-        listen(*endpoint_iterator,ec);
+        listen(*endpoints.begin(),ec);
```
Comment (toonetown) [inline websocketpp/transport/asio/endpoint.hpp:529]: Personal preference (for readability) is to use parenthesis when dereferencing like this so it is clear to which it is applying.  Something like this:
```suggestion
        listen(*(endpoints.begin()),ec);
```

File: websocketpp/transport/asio/endpoint.hpp [hunk 6]
```diff
@@ -663,42 +661,42 @@ class endpoint : public config::socket_type {
...
     std::size_t poll_one() {
-        return m_io_service->poll_one();
+        return m_io_context->poll_one();
     }
 
-    /// wraps the reset method of the internal io_service object
+    /// wraps the restart method of the internal io_context object
     void reset() {
-        m_io_service->reset();
+        m_io_context->restart();
```
Comment (toonetown) [inline websocketpp/transport/asio/endpoint.hpp:694]: I also suggest renaming this function to `restart` to match the fact that it's just passing through to the underlying `io_context` object.  If you make this change, you ALSO need to change what is called in https://github.com/zaphoyd/websocketpp/blob/b9aeec6eaf3d5610503439b4fae3581d9aff08e8/examples/testee_client/testee_client.cpp#L126

File: websocketpp/transport/asio/endpoint.hpp [hunk 7]
```diff
@@ -995,10 +993,10 @@ class endpoint : public config::socket_type {
 
     void handle_resolve(transport_con_ptr tcon, timer_ptr dns_timer,
         connect_handler callback, lib::asio::error_code const & ec,
-        lib::asio::ip::tcp::resolver::iterator iterator)
+        lib::asio::ip::tcp::resolver::results_type endpoints)
```
Comment (toonetown) [inline websocketpp/transport/asio/endpoint.hpp:996]: Suggest renaming the parameter as `results` to match `results_type` instead of `endpoints`

**Review by toonetown — APPROVED** [review]
Please note that all of these are merely suggestions - this patch is extremely useful as-is and I don't see any "blocking" issues with it.  The suggestions I provide are just based off of reconciliation with the patch work that I did and mainly revolve around naming differences and conventions.

Additionally (outside the individual suggestions below), there is also one reference remaining to `io_service` in https://github.com/zaphoyd/websocketpp/blob/b9aeec6eaf3d5610503439b4fae3581d9aff08e8/roadmap.md?plain=1#L19 which would probably be worth changing as well.

**Comment by amini-allight** [comment]
@toonetown Thanks for the feedback, I've implemented almost all of your suggestions!

I left two out:
- I didn't change the roadmap because I'm honestly unsure if that line should be in the roadmap to begin with. There is an example called `external_io_service` (hopefully soon to be called `external_io_context`) which seems to demonstrate exactly that feature in use.
- I didn't change the name of `websocketpp::transport::asio::endpoint<config>::reset` because this is a public function on the public base class of `websocketpp::client`. As I understand it that makes it part of the user-facing API so renaming it might break somebody's downstream project and I think we should aim for a drop-in replacement for the broken version.

Let me know if there's any other work that needs doing.

**Review by toonetown — APPROVED** [review]
Looks great!  Your reasoning make perfect sense.  Nice work!

**Comment by Kinokin** [comment]
@amini-allight 
Tried your changes and it worked well with plain boost 1.87. Thanks a lot!

In order to check for expected future problems I tried to build with BOOST_ASIO_NO_DEPRECATED defined,
sadly no I got new errors.

Any chance to fix the remaining references on deprecated asio features?

**Comment by Kinokin** [comment]
@amini-allight 

problems I see in my project are about strand::wrap

.../websocketpp/transport/asio/connection.hpp:327:45: error: no member named 'wrap' in 'boost::asio::io_context::strand'
  327 |             new_timer->async_wait(m_strand->wrap(lib::bind(
      |                                   ~~~~~~~~~~^
.../websocketpp/websocketpp/transport/asio/connection.hpp:638:27: error: no member named 'wrap' in 'boost::asio::io_context::strand'
  638 |                 m_strand->wrap(lib::bind(
      |                 ~~~~~~~~~~^
.../websocketpp/websocketpp/transport/asio/connection.hpp:721:27: error: no member named 'wrap' in 'boost::asio::io_context::strand'
  721 |                 m_strand->wrap(lib::bind(
      |                 ~~~~~~~~~~^
.../websocketpp/websocketpp/transport/asio/connection.hpp:859:27: error: no member named 'wrap' in 'boost::asio::io_context::strand'
  859 |                 m_strand->wrap(make_custom_alloc_handler(
      |                 ~~~~~~~~~~^
.../websocketpp/websocketpp/transport/asio/connection.hpp:928:27: error: no member named 'wrap' in 'boost::asio::io_context::strand'
  928 |                 m_strand->wrap(make_custom_alloc_handler(
      |                 ~~~~~~~~~~^
.../websocketpp/websocketpp/transport/asio/connection.hpp:968:27: error: no member named 'wrap' in 'boost::asio::io_context::strand'
  968 |                 m_strand->wrap(make_custom_alloc_handler(
      |                 ~~~~~~~~~~^
.../websocketpp/websocketpp/transport/asio/connection.hpp:1033:69: error: no member named 'wrap' in 'boost::asio::io_context::strand'
 1033 |             lib::asio::post(m_io_context->get_executor(), m_strand->wrap(handler));
      |                                                           ~~~~~~~~~~^
.../websocketpp/websocketpp/transport/asio/connection.hpp:1042:69: error: no member named 'wrap' in 'boost::asio::io_context::strand'
 1042 |             lib::asio::post(m_io_context->get_executor(), m_strand->wrap(handler));
      |                                                           ~~~~~~~~~~^
.../websocketpp/websocketpp/transport/asio/endpoint.hpp:933:37: error: no member named 'wrap' in 'boost::asio::io_context::strand'
  933 |                 tcon->get_strand()->wrap(lib::bind(
      |                 ~~~~~~~~~~~~~~~~~~~~^
.../websocketpp/websocketpp/transport/asio/endpoint.hpp:805:37: error: no member named 'wrap' in 'boost::asio::io_context::strand'
  805 |                 tcon->get_strand()->wrap(lib::bind(
      |                 ~~~~~~~~~~~~~~~~~~~~^

My application looks fine except of three errors. Didn't check if application uses deprecated feature or errors are caused by above errors

**Comment by amini-allight** [comment]
@Kinokin I've added a new commit which addresses this. Let me know if you find any other deprecations which need fixing.

**Comment by Kinokin** [comment]
@amini-allight
Got build success using the lastest commits using boost 1.87.0 and BOOST_ASIO_NO_DEPRECATED

Most failures in my test application went away and I managed to fix the last one.
And the test was successful!

Again, thanks a lot!

**Comment by MGraefe** [comment]
Thanks for these fixes! Added it to our application, compiles and works just fine.

**Comment by loqs** [comment]
@amini-allight should the version check for boost in CMakeLists.txt not have its version increased from 1.39.0 and a version check added to SConstruct? Similarly if the minimum version of boost is now above 1.43.0 then should https://github.com/zaphoyd/websocketpp/blob/master/websocketpp/common/random.hpp#L58 be changed?

**Comment by zaphoyd** [comment]
I assume this change removes compatibility with the older versions of Asio?

**Comment by toonetown** [comment]
@zaphoyd - yeah - will break if using versions of asio that are **_more than 8 years old_**. Versions that old are very unlikely to be encountered in the wild…and this change is required to support **_current_** asio and boost. 

There has been an 8-year deprecation time window - seems a change like this is just in keeping up with the times. If you have a requirement to use 8-year-old asio, you can use older websocket++ as well.

**Comment by zaphoyd** [comment]
Noted. As I review I am trying to assess whether some sort of fallback is needed. I think I agree that at this point falling back to an older version of WebSocket++ is likely to be the best solution for that narrow case.

Also, thanks for your (and others here) work on this. Going to try and get this reviewed and packaged up into an official release.

**Comment by amini-allight** [comment]
@zaphoyd To expand on what toonetown said compatibility with boost 1.66.0 and onwards should be preserved but I have not tested this extensively (I can do so if you like). Any version before that will not work because, at a minimum, `boost::asio::io_context` didn't exist yet, which we are now using in place of `boost::asio::io_service` all throughout the project. Examining the Boost compatibility preprocessor macros in `random.hpp` (which were removed) it appears that the current `develop` branch doesn't support versions earlier than 1.43.0 anyway, so 1.43.0 — 1.65.1 inclusive is all we're losing.

The CMake version bump probably also introduces incompatibility with some old CMake versions but I'm not sure it's possible to win with CMake: an older specified version causes incompatibility with newer executables just as much as a newer specified version causes incompatibility with older executables.

Great to hear you're looking to merge this!

**Comment by maxoodf** [comment]
@zaphoyd Are there any plans to merge this pull request?
One more question - are there any plans to release the next version (0.8.3)?
Thank you.

**Comment by Nick7K** [comment]
Any progress on getting this back into vcpkg?

**Comment by cricri32** [comment]
> Any progress on getting this back into vcpkg?

This request need to be reviewed and merged so we can open an issue on vcpkg, see:

https://github.com/microsoft/vcpkg/pull/42678#issuecomment-2902780101

@zaphoyd @toonetown  could you please, review it?

**Comment by enelielz** [comment]
I'm also coming here from the vcpkg repo, @zaphoyd  will youmerge this request?

**Comment by cricri32** [comment]
> I'm also coming here from the vcpkg repo, @zaphoyd will youmerge this request?

Hey have you succeeded on compiling it?

**Comment by erikpaulo22** [comment]
Everyone coming here from the vcpkg issue D:

**Comment by sidarnnt** [comment]
+1

**Comment by Wiminii** [comment]
bump

**Comment by sergnejk2** [comment]
> Everyone coming here from the vcpkg issue D:

:D

**Comment by utopyap** [comment]
@zaphoyd will you merge it?

**Comment by garbanrd09** [comment]
bump

**Comment by contapxgdevil-ops** [comment]
Is the project deprecated?

**Comment by limann77** [comment]
@vcpkg people: Spamming this issue doesn't help fixing it.

**Comment by erikpaulo22** [comment]
@limann77  ???

**Review by AsnIIe — APPROVED** [review]
